---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: project-manager-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBaYF3JYtwvOGzhoZpW4v/BU9Oim6cfnfevhJOIZ9prNb6542Fqdtg0CCdNvdCxe5FXc9VIUp6z7MZtERh7p0SVe6S0OAtUMwX/q5Jz78ZKG+NcE2nmKiBDa7+Kff7hMgxDRO3cNaNG0tMwP4PXpLajx4bT3bHAC1VlOICj9kzVMA0KwDqv3NlS523w8bivm7qZ9ApfdmvxPkk5bdlJEjEpKPwz/erL+D+BBEukZ1Vw5i/jPB65ub14lWniU9pblXEthjnQti6Y3FlGMtOoLCtCuDQKj9taSptiR2o2LNV0Y6bklZ9Ztfp6vyOSws7SWPSya6U3+M0SiMjjzdf5zwhP63nZmRo5Dads6Yn9DOzUMMvsb/aLRnwJBvPYiEcGBM/+gjW52+OO8QOQOy0bWouhetnJo72pntMA3jQZSKkXJJlVb5etLKN+Dt62OpClufo6lg3zvx4+cnf9HZLIgdGRuwA38ttbgFTTgxGev3+ZoEymv4RRke1e5AcbLAD8iP1Bqm6HuLe8W503DwumsV0ywd3fHqdcSe6Ox4J+E8kTk+wH5d+i0WeQ7+OYkITDNK1RylujEaXsTGKkgYUo8tlmLp0OfFz9iX3phTP7YSV4CasBAUk2bM7+73EYh59tC2AYD8FC7+MJ6eDh/U53HXgiNGI1miatsV/HSH9mxfMcATs3ibbjcCY3v75az8dp3Cuhiu/qWadilZ9lc740bMGxTt/hkD9fBQNHVDoticHXH7DJlGKB4M8UEwhz/eK9BSIdxpW0fAKtYPqXoxsTiB4oCdixkvr/PX23MBLxgCkA1MZNchn9QJXOk9Kqet06lLzieldu0E3F9vFpAsprzALmaLk3nWsmc7P8LqfVsnCqMrlBQ7+vOqKdThQ9U5XqgOfDckq2SG9V2cwQL4CZUYtnYNfKT4DjkAp/PZklAaBSktJYcSTj/t9UiQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: project-manager-staging
    type: kubernetes.io/dockerconfigjson
