apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/name: project-manager
spec:
  selector:
    app.kubernetes.io/name: project-manager
  ports:
    - name: http
      port: 80
      targetPort: 8000
