apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres/sealedsecret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml

namespace: project-manager-staging

patches:
  - target:
      kind: Namespace
      name: project-manager
    patch: |-
      - op: replace
        path: /metadata/name
        value: project-manager-staging

  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pj-staging.ja-zum-leben.at
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pj-staging.ja-zum-leben.at
